# Generated by Django 3.1.2 on 2020-10-27 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='symbol_lookup_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='AAPL,TSLA,SBUX,...', max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Symbols',
            },
        ),
    ]
