# Generated by Django 3.1.2 on 2020-10-31 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='investment_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Investment Types',
            },
        ),
        migrations.CreateModel(
            name='portfolio_idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea_name', models.CharField(help_text='What do you want to call this portfolio?', max_length=256)),
                ('symbol', models.CharField(help_text='AAPL,TSLA,SBUX,...', max_length=5)),
                ('symbol_sector', models.CharField(max_length=500)),
                ('investment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.investment_type')),
            ],
            options={
                'verbose_name_plural': 'Portfolio Ideas',
            },
        ),
    ]
